name: LeetCode Sync

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    # Runs every day at 00:00 UTC (adjust as needed)
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.0.1
        with:
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional configurations:
          # LANG: "python" # Specify preferred language (e.g., python, java, cpp, javascript, typescript, go, rust, php, kotlin, csharp, ruby, swift)
          # COMMIT_BY_PROBLEM_NAME: "false" # Set to 'true' to use problem name for commit messages
          # CODE_FORMAT_COMMIT_NAME: "false" # Set to 'true' to format commit messages
